const rawQuestions = {
    de: [
        "Wenn du mit einer einzigen kleinen Straftat ungestraft davonkommen könntest, welche wäre das?",
        "Wenn du morgen deinen Namen ändern müsstest, welchen würdest du wählen und warum?",
        "Was ist ein seltsam spezifischer Dealbreaker für dich in einer Freundschaft oder Beziehung?",
        "Wenn du von jetzt auf gleich ein absoluter Weltklasse-Experte in einem Nischenthema werden könntest, welches wäre das?",
        "Wenn du heimlich den Google-Suchverlauf einer beliebigen Person aus der letzten Woche sehen könntest, wen würdest du wählen?",
        "An welches Kompliment, das dir jemand vor Jahren gemacht hat, musst du heute noch denken?",
        "Wann hast du dich das letzte Mal von jemandem so richtig verstanden gefühlt?",
        "Was liebst du an dir selbst, das absolut nichts mit deinem Aussehen oder deinen Erfolgen zu tun hat?",
        "Wenn du dich bei einer Person aus deiner Vergangenheit entschuldigen könntest, ohne dass es ein Nachspiel hat – wer wäre das und was würdest du sagen?",
        "An welche Überzeugung hast du vor fünf Jahren noch felsenfest geglaubt, der du heute überhaupt nicht mehr zustimmst?",
        "Was tolerierst du momentan in deinem Leben, obwohl du genau weißt, dass du es nicht tun solltest?",
        "Was ist der größte Unterschied zwischen dem, wie du im Inneren bist, und dem, wie du dich nach außen zeigst?",
        "Was ist eine harte Wahrheit über dich selbst, die du in letzter Zeit akzeptieren musstest?",
        "Wenn du jemanden treffen würdest, der exakt so ist wie du: Was wäre das Schwierigste daran, eine Beziehung mit dieser Person aufzubauen?",
        "Wenn du nächstes Jahr dein Gedächtnis verlieren würdest: Welche Erinnerung würdest du um jeden Preis behalten wollen?",
        "Wenn dein zukünftiges Ich irgendwann auf dein jetziges Leben zurückblickt: Was wirst du wohl am meisten vermissen?",
        "Wenn du heute sterben würdest: Was wäre deine größte unerledigte Sache im Leben?",
        "Welche Frage würdest du gerne öfter gestellt bekommen?",
        "Wenn du verhaftet werden würdest – wofür wäre es deiner Meinung nach am wahrscheinlichsten?",
        "Du kannst für einen Tag eine beliebige Superkraft haben – wofür entscheidest du dich?",
        "Wie würde deine beste Freundin oder dein bester Freund dich in drei Worten beschreiben?",
        "Was ist dein verstecktes Talent?",
        "Du hast drei freie Plätze bei deiner Dinner Party – lebend oder verstorben, wen lädst du ein?",
        "Was ist das Schönste, das je jemand zu dir gesagt hat?",
        "Was hast du aus deiner letzten Beziehung gelernt?",
        "Welche Lebenserfahrung hat dich zu dem Menschen gemacht, der du heute bist?",
        "Was hätte dein jüngeres Ich unbedingt hören müssen?",
        "Der Mensch, den du am meisten liebst, stirbt morgen. Du hast einen 60-Sekunden-Anruf – was sagst du?",
        "Wer hat dir den besten Lebensratschlag gegeben und was war es?",
        "Wann fühlst du dich am lebendigsten?",
        "Welche Beziehung in deinem Leben verdient mehr Aufmerksamkeit?",
        "Wenn dein Leben ein Film wäre – was würde der Zuschauer dich anschreien zu tun?",
        "Was hast du im letzten Jahr über dich selbst herausgefunden?"
    ],
    en: [
        "If you could get away with one minor crime, what would it be?",
        "If you had to change your name tomorrow, what would you choose and why?",
        "What is a weirdly specific dealbreaker for you in a friendship or relationship?",
        "If you could instantly become a world-class expert in one niche subject, what would it be?",
        "If you could look at any one person's Google search history for the last week without them knowing, who would you choose?",
        "What is a compliment someone gave you years ago that you still think about?",
        "When was the last time you felt truly understood by someone?",
        "What is something you love about yourself that has nothing to do with your appearance or achievements?",
        "If you could apologize to one person from your past with no consequences, who would it be and what would you say?",
        "What is a belief you held fiercely five years ago that you completely disagree with now?",
        "What are you currently tolerating in your life that you know you shouldn't be?",
        "What is the difference between who you are on the inside and how you present yourself to the world?",
        "What is a hard truth you’ve had to accept about yourself recently?",
        "If you met someone exactly like you, what would be the hardest part about building a relationship with them?",
        "If you knew you were going to lose your memory next year, what is the one memory you would fight hardest to hold onto?",
        "What do you think your future self will look back on right now and miss the most?",
        "If you died today, what would be your biggest unfinished piece of business?",
        "What is a question you wish people asked you more often?",
        "If you were arrested, what do you think it'd be for?",
        "You can have any superpower for a day, what are you choosing?",
        "How would your best friend describe you in 3 words?",
        "What's your hidden talent?",
        "You have 3 spaces at your dinner party, alive or dead, who are you inviting?",
        "What's the most beautiful thing you've ever been told?",
        "What did you learn from your last relationship?",
        "Which life experience shaped who you are today?",
        "What one thing did your younger self need to hear?",
        "The person you cherish most is going to die tomorrow. You have a 60-second call, what do you say?",
        "Who gave you the best life advice, what did they say?",
        "When do you feel most alive?",
        "Which relationship in your life deserves more attention?",
        "If your life were a movie, what would the viewer be screaming at you to do?",
        "What's something you've discovered about yourself in the past year?"
    ]
};
